server:
  port: 8080  # ????

minio:
  endpoint: http://172.27.177.119:9000  # MinIO??????????????
  access-key: admin            # MinIO???????minioadmin?
  secret-key: admin123456           # MinIO???????minioadmin?
  bucket-name: doc          # ??????????MinIO???

# ?????????Vue?????8081????
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    cors:
      allowed-origins: "*"           # ???????????????????
      allowed-methods: "*"
      allowed-headers: "*"
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 20MB
      # 整个请求最大大小
      max-request-size: 20MB
  data:
    mongodb:
      uri: mongodb://172.27.177.119:27017
      database: blocks
